language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules/cypress/dist

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - next
    - /^greenkeeper.*$/

stages:
  - name: greenkeeper-routes-update
    if: branch =~ ^greenkeeper/@octokit/routes
  - test
  - name: release
    if: branch = master AND type IN (push)

install: npm ci

jobs:
  include:
    - stage: test
      # spead up build times by removing unneeded dev dependencies
      before_install:
        - npm install -g npm@6
        - npm uninstall leakage semantic-release
      node_js: 6
      script:
        - npm run start-fixtures-server &
        - sleep 3 # give server some time to start
        - npm run test
    - node_js: 8
      # spead up build times by removing unneeded dev dependencies
      before_install: npm uninstall leakage cypress semantic-release
      script:
        - npm run start-fixtures-server &
        - sleep 3 # give server some time to start
        - npm run test
    - node_js: 10
      # g++-4.8 required for "leakage"
      # see https://github.com/andywer/leakage/tree/a10c0f6da542b238c73fe485e0317c1f1bce77ee#travis-ci
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      # spead up build times by removing unneeded dev dependencies
      before_install: npm uninstall cypress semantic-release
      env: Node 10, memory test, coverage upload
      script:
        - npm run start-fixtures-server &
        - sleep 3 # give server some time to start
        - npm run test
        - npm run test:memory
        # ignore error as coveralls is down frequently so we ignore errors
        - npx nyc report --reporter=text-lcov | npx coveralls || true
    - node_js: lts/*
      # spead up build times by removing unneeded dev dependencies
      before_install: npm uninstall leakage semantic-release
      env: browser tests
      addons:
        apt:
          packages:
            # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
            - libgconf-2-4
      script:
        - npm run start-fixtures-server &
        - sleep 3 # give server some time to start
        - npm run test:browser
    - node_js: lts/*
      sudo: required
      addons:
        chrome: stable
      # spead up build times by removing unneeded dev dependencies
      before_install: npm uninstall leakage cypress semantic-release
      env: bundle size, typescript validation
      script:
        # test bundle size
        - npm run build:browser
        - npx bundlesize
        # test typescript definitions
        - npm run validate:ts
    - node_js: lts/*
      env: folder size
      install: npm install --production
      script: npx get-folder-size --folder=node_modules/ | grep "^[01]\."

    # when updating @octokit/routes, run "generate-routes" script and push
    # new routes.json file to the pull request
    - stage: greenkeeper-routes-update
      node_js: lts/*
      # spead up build times by removing unneeded dev dependencies
      before_install: npm uninstall leakage cypress semantic-release
      script:
        - git checkout $TRAVIS_BRANCH
        - npm run generate-routes
        # commit changes and push back to branch on GitHub. If there are no changes then exit without error
        - 'git commit plugins/rest-api-endpoints/routes.json -m "build: routes" --author="Octokit Bot <octokitbot@martynus.net>" && git push "https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG" ${TRAVIS_BRANCH} || true'

    # build assets and release new version with semantic-release
    - stage: release
      node_js: lts/*
      # spead up build times by removing unneeded dev dependencies
      before_install: npm uninstall leakage cypress
      env: semantic-release
      script:
        - npm run build:ts
        - npm run build:browser
        - npm run generate-bundle-report
        - npx semantic-release
