language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules/cypress/dist

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

stages:
  - test
  - name: release
    if: branch = master AND type IN (push)

jobs:
  include:
    - stage: test
      node_js: 6
      script:
        - npm run start-fixtures-server &
        - sleep 3 # give server some time to start
        - npm run test
    - node_js: 8
      script:
        - npm run start-fixtures-server &
        - sleep 3 # give server some time to start
        - npm run test
    - node_js: 9
      script:
        - npm run start-fixtures-server &
        - sleep 3 # give server some time to start
        - npm run test
        # coverage
        - npm run coverage:upload
    - node_js: lts/*
      env: BROWSER_TESTS
      script:
        # make puppeteer work
        - sudo chown root /opt/google/chrome/chrome-sandbox
        - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        # test in node & browser
        - npm run start-fixtures-server &
        - sleep 3 # give server some time to start
        - npm run test:browser
    - node_js: lts/*
      env: BUNDLE_SIZE,TYPESCRIPT_VALIDATION
      script:
        # test bundle size
        - npm run build:browser
        - npx bundlesize
        # test typescript definitions
        - npm run validate:ts
    # release stage: run semantic release & update the docs
    - stage: release
      node_js: lts/*
      script:
        - npm run build:flow
        - npm run build:ts
        - npm run build:browser
        - npm run generate-bundle-report
        - npm run semantic-release
    - node_js: lts/*
      script:
        - npm run build:docs
        - npm run deploy-docs
